In [214]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from deep_translator import GoogleTranslator
import seaborn as sns

In [219]:
df_th = pd.read_excel("/Users/srisuphachawla/Documents/DataScience_Projects/LogisticsDataset/otp_69_01_68.xlsx")

In [220]:
df = pd.read_csv("/Users/srisuphachawla/Documents/DataScience_Projects/LogisticsDataset/Thai_logistics_inEnglishProcess")

In [221]:
# Restore Thai district names
df["district_origin"] = df_th["district_origin"]
df["district_destination"] = df_th["district_destination"]

# Restore Thai subdistrict names
df["subdistrict_origin"] = df_th["subdistrict_origin"]
df["subdistrict_destination"] = df_th["subdistrict_destination"]

In [222]:
df

,id,year,month,product,subdistrict_origin,district_origin,province_origin,subdistrict_destination,district_destination,province_destination,trips,shipping,average_distance,average_duration,average_speed
0,1,2568,January,paddy,ตาลสุม,ตาลสุม,Ubon Ratchathani,กุดชมภู,พิบูลมังสาหาร,Ubon Ratchathani,405,9033,21.43,32.66,39.37
1,2,2568,January,paddy,พระอาจารย์,องครักษ์,Nakhon Nayok,ท่าสะอ้าน,บางปะกง,Chachoengsao,403,8981,63.93,91.61,41.87
2,3,2568,January,paddy,คำหว้า,ตาลสุม,Ubon Ratchathani,กุดชมภู,พิบูลมังสาหาร,Ubon Ratchathani,384,8567,21.89,39.93,32.89
3,4,2568,January,paddy,วังม้า,ลาดยาว,Nakhon Sawan,ท่าฉนวน,มโนรมย์,Chai Nat,331,7376,67.10,84.94,47.40
4,5,2568,January,paddy,เตย,ม่วงสามสิบ,Ubon Ratchathani,ยางโยภาพ,ม่วงสามสิบ,Ubon Ratchathani,320,7143,18.50,26.89,41.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346966,346967,2568,August,car,ทุ่งสุขลา,ศรีราชา,Chonburi,สุรศักดิ์,ศรีราชา,Chonburi,1,17,18.61,52.88,21.12
346967,346968,2568,August,car,ทุ่งสุขลา,ศรีราชา,Chonburi,ไร่ส้ม,เมืองเพชรบุรี,Phetchaburi,1,17,236.98,332.48,42.77
346968,346969,2568,August,car,ทุ่งสุขลา,ศรีราชา,Chonburi,บางแก้ว,เมืองสมุทรสงคราม,Samut Songkhram,1,17,177.05,245.00,43.36
346969,346970,2568,August,car,ทุ่งสุขลา,ศรีราชา,Chonburi,คันนายาว,เขตคันนายาว,Bangkok,1,17,105.57,156.45,40.49
346970,346971,2568,August,car,ทุ่งสุขลา,ศรีราชา,Chonburi,บ้านใหม่,เมืองนครราชสีมา,Nakhon Ratchasima,1,17,348.39,533.02,39.22

In [223]:
df.describe()

,id,year,trips,shipping,average_distance,average_duration,average_speed
count,346971.000000,346971.0,346971.000000,346971.000000,346971.000000,346971.000000,346971.000000
mean,173486.000000,2568.0,28.031945,776.947598,121.397510,156.876851,43.930749
std,100162.044463,0.0,163.843404,4922.222475,137.645385,175.312006,9.426172
min,1.000000,2568.0,1.000000,6.000000,3.000000,4.500000,15.000000
25%,86743.500000,2568.0,2.000000,40.000000,29.120000,44.960000,38.060000
50%,173486.000000,2568.0,5.000000,121.000000,74.950000,99.540000,45.000000
75%,260228.500000,2568.0,15.000000,369.000000,158.125000,199.210000,50.620000
max,346971.000000,2568.0,29978.000000,899332.000000,1480.180000,4444.170000,65.000000

In [224]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 346971 entries, 0 to 346970
Data columns (total 15 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       346971 non-null  int64
 1   year                     346971 non-null  int64
 2   month                    346971 non-null  object
 3   product                  346971 non-null  object
 4   subdistrict_origin       346971 non-null  object
 5   district_origin          346971 non-null  object
 6   province_origin          346971 non-null  object
 7   subdistrict_destination  346971 non-null  object
 8   district_destination     346971 non-null  object
 9   province_destination     346971 non-null  object
 10  trips                    346971 non-null  int64
 11  shipping                 346971 non-null  int64
 12  average_distance         346971 non-null  float64
 13  average_duration         346971 non-null  float64
 14  average_speed            346971 non-null  float64
dtypes: float64(3), int64(4), object(8)
memory usage: 39.7+ MB

In [225]:
print(df.nunique())

id                         346971
year                            1
month                           5
product                        21
subdistrict_origin           4138
district_origin               877
province_origin                77
subdistrict_destination      5447
district_destination          917
province_destination           77
trips                        1644
shipping                     8753
average_distance            48140
average_duration            55370
average_speed                4995
dtype: int64

In [226]:
# convert Thai Calendar to Gregorian
df['year'] = df['year'] - 543
df["year"] = df["year"].astype(str)

### Fixing Automatic Translations

In [227]:
df["province_destination"].sort_values().unique()

array(['Amnat Charoen', 'Ang Thong', 'Ayutthaya', 'Bangkok', 'Bueng Kan',
       'Buriram', 'Chachoengsao', 'Chai Nat', 'Chaiyaphum', 'Chanthaburi',
       'Chiang Mai', 'Chiang Rai', 'Chonburi', 'Chumphon', 'Kalasin',
       'Kamphaeng Phet', 'Kanchanaburi', 'Khon Kaen', 'Lampang',
       'Lamphun', 'Lop Buri', 'Mae Hong Son', 'Maha Sarakham', 'Mukdahan',
       'Nakhon Nayok', 'Nakhon Pathom', 'Nakhon Phanom',
       'Nakhon Ratchasima', 'Nakhon Sawan', 'Nakhon Si Thammarat', 'Nan',
       'Narathiwat', 'Nong Bua Lamphu', 'Nong Khai', 'Nonthaburi',
       'Pathum Thani', 'Pattani', 'Phangnga', 'Phatthalung', 'Phayao',
       'Phetchabun', 'Phetchaburi', 'Phichit', 'Phitsanulok', 'Phuket',
       'Prachin Buri', 'Prachuap Khiri Khan', 'Ranong', 'Ratchaburi',
       'Rayong', 'Roi Et', 'Sa Kaeo', 'Sakon Nakhon', 'Samut Prakan',
       'Samut Sakhon', 'Samut Songkhram', 'Saraburi', 'Satun',
       'Si Sa Ket', 'Sing Buri', 'Songkhla', 'Sukhothai', 'Suphan Buri',
       'Surat Thani', 'Surin', 'Sword', 'Trang', 'Trat',
       'Ubon Ratchathani', 'Udon Thani', 'Uthai Thani', 'Uttaradit',
       'Yala', 'Yasothon', 'at all', 'dry', 'spread'], dtype=object)

In [228]:
province_fix = {
    "Sword": "Tak",
    "at all": "Phrae",
    "spread": "Krabi",
    "dry": "Loei",
    "Phangnga": "Phang Nga"
}

df["province_destination"] = df["province_destination"].replace(province_fix)
df["province_origin"] = df["province_origin"].replace(province_fix)

In [229]:
origin_lookup = (
    pd.DataFrame({
        "Thai": df_th["district_origin"],
        "English": df["district_origin"]
    })
    .drop_duplicates()
    .sort_values("Thai")
)

origin_lookup.to_excel(
    "origin_district_lookup.xlsx",
    index=False
)

In [230]:
df.head(40)

,id,year,month,product,subdistrict_origin,district_origin,province_origin,subdistrict_destination,district_destination,province_destination,trips,shipping,average_distance,average_duration,average_speed
0,1,2025,January,paddy,ตาลสุม,ตาลสุม,Ubon Ratchathani,กุดชมภู,พิบูลมังสาหาร,Ubon Ratchathani,405,9033,21.43,32.66,39.37
1,2,2025,January,paddy,พระอาจารย์,องครักษ์,Nakhon Nayok,ท่าสะอ้าน,บางปะกง,Chachoengsao,403,8981,63.93,91.61,41.87
2,3,2025,January,paddy,คำหว้า,ตาลสุม,Ubon Ratchathani,กุดชมภู,พิบูลมังสาหาร,Ubon Ratchathani,384,8567,21.89,39.93,32.89
3,4,2025,January,paddy,วังม้า,ลาดยาว,Nakhon Sawan,ท่าฉนวน,มโนรมย์,Chai Nat,331,7376,67.10,84.94,47.40
4,5,2025,January,paddy,เตย,ม่วงสามสิบ,Ubon Ratchathani,ยางโยภาพ,ม่วงสามสิบ,Ubon Ratchathani,320,7143,18.50,26.89,41.28
5,6,2025,January,paddy,วังม้า,ลาดยาว,Nakhon Sawan,ดงเสือเหลือง,โพธิ์ประทับช้าง,Phichit,316,7040,94.18,115.27,49.02
6,7,2025,January,paddy,ศีรษะกระบือ,องครักษ์,Nakhon Nayok,บางลูกเสือ,องครักษ์,Nakhon Nayok,262,5849,11.83,25.17,28.20
7,8,2025,January,paddy,ลาดยาว,ลาดยาว,Nakhon Sawan,สร้อยทอง,ตาคลี,Nakhon Sawan,247,5513,128.29,151.32,50.87
8,9,2025,January,paddy,แม่ทะ,แม่ทะ,Lampang,สมอแข,เมืองพิษณุโลก,Phitsanulok,229,5099,222.72,257.62,51.87
9,10,2025,January,paddy,ทุ่งเทิง,เดชอุดม,Ubon Ratchathani,น้ำอ้อม,เกษตรวิสัย,Roi Et,196,4374,265.91,336.79,47.37
10,11,2025,January,paddy,ทุ่งเทิง,เดชอุดม,Ubon Ratchathani,โนนค้อ,โนนคูณ,Si Sa Ket,186,4141,46.22,58.73,47.22
11,12,2025,January,paddy,ฆะมัง,ชุมแสง,Nakhon Sawan,ดงเสือเหลือง,โพธิ์ประทับช้าง,Phichit,172,3830,57.59,67.90,50.89
12,13,2025,January,paddy,ม่วงสามสิบ,ม่วงสามสิบ,Ubon Ratchathani,กุดชมภู,พิบูลมังสาหาร,Ubon Ratchathani,171,3805,80.54,84.99,56.86
13,14,2025,January,paddy,หนองกรด,บรรพตพิสัย,Nakhon Sawan,นรสิงห์,ป่าโมก,Ang Thong,171,3805,193.92,229.60,50.68
14,15,2025,January,paddy,พืชอุดม,ลำลูกกา,Pathum Thani,หมอนทอง,บางน้ำเปรี้ยว,Chachoengsao,168,3753,31.54,40.99,46.17
15,16,2025,January,paddy,พนมรอก,ท่าตะโก,Nakhon Sawan,ตลุก,สรรพยา,Chai Nat,156,3468,85.52,101.88,50.37
16,17,2025,January,paddy,ก่อเอ้,เขื่องใน,Ubon Ratchathani,เมืองใต้,เมืองศรีสะเกษ,Si Sa Ket,153,3416,71.99,103.62,41.69
17,18,2025,January,paddy,หนองกระเจา,ชุมแสง,Nakhon Sawan,วังไทร,คลองขลุง,Kamphaeng Phet,152,3390,112.97,134.67,50.33
18,19,2025,January,paddy,กุดเลาะ,เกษตรสมบูรณ์,Chaiyaphum,หนองนาแซง,เมืองชัยภูมิ,Chaiyaphum,149,3313,80.50,132.05,36.58
19,20,2025,January,paddy,ห้วยถั่วเหนือ,หนองบัว,Nakhon Sawan,ห้วยถั่วเหนือ,หนองบัว,Nakhon Sawan,133,2976,14.17,24.35,34.92
20,21,2025,January,paddy,ดงเสือเหลือง,โพธิ์ประทับช้าง,Phichit,วังม้า,ลาดยาว,Nakhon Sawan,113,2510,92.83,111.75,49.84
21,22,2025,January,paddy,นาวุ้ง,เมืองเพชรบุรี,Phetchaburi,ถนนขาด,เมืองนครปฐม,Nakhon Pathom,111,2485,118.11,137.41,51.57
22,23,2025,January,paddy,สร้อยทอง,ตาคลี,Nakhon Sawan,ท่าสะอ้าน,บางปะกง,Chachoengsao,108,2407,228.85,258.75,53.07
23,24,2025,January,paddy,แม่สาย,แม่สาย,Chiang Rai,แม่จัน,แม่จัน,Chiang Rai,108,2407,33.97,45.29,45.00
24,25,2025,January,paddy,โคกสว่าง,สำโรง,Ubon Ratchathani,สำโรง,อุทุมพรพิสัย,Si Sa Ket,107,2381,98.73,131.78,44.95
25,26,2025,January,paddy,เซเป็ด,ตระการพืชผล,Ubon Ratchathani,คำเจริญ,ตระการพืชผล,Ubon Ratchathani,107,2381,11.23,22.65,29.75
26,27,2025,January,paddy,พระอาจารย์,องครักษ์,Nakhon Nayok,พระอาจารย์,องครักษ์,Nakhon Nayok,102,2278,12.43,23.76,31.39
27,28,2025,January,paddy,โพรงอากาศ,บางน้ำเปรี้ยว,Chachoengsao,บางเตย,บ้านสร้าง,Prachin Buri,102,2278,22.49,27.73,48.66
28,29,2025,January,paddy,บ้านค่าย,เมืองชัยภูมิ,Chaiyaphum,หัวทะเล,เมืองนครราชสีมา,Nakhon Ratchasima,101,2252,97.51,112.97,51.79
29,30,2025,January,paddy,ห้วยถั่วเหนือ,หนองบัว,Nakhon Sawan,หนองกระเจา,ชุมแสง,Nakhon Sawan,97,2174,17.88,20.25,52.98
30,31,2025,January,paddy,บางเตย,บ้านสร้าง,Prachin Buri,กันจุ,บึงสามพัน,Phetchabun,93,2071,270.90,296.87,54.75
31,32,2025,January,paddy,บ้านค่าย,เมืองชัยภูมิ,Chaiyaphum,โคกสูง,เมืองนครราชสีมา,Nakhon Ratchasima,92,2045,78.41,95.32,49.36
32,33,2025,January,paddy,หนองกระเจา,ชุมแสง,Nakhon Sawan,ห้วยถั่วเหนือ,หนองบัว,Nakhon Sawan,92,2045,14.56,16.01,54.57
33,34,2025,January,paddy,ศรีจุฬา,เมืองนครนายก,Nakhon Nayok,ดอนฉิมพลี,บางน้ำเปรี้ยว,Chachoengsao,91,2019,34.65,54.26,38.32
34,35,2025,January,paddy,อาษา,บ้านนา,Nakhon Nayok,บางลูกเสือ,องครักษ์,Nakhon Nayok,91,2019,30.02,40.13,44.88
35,36,2025,January,paddy,หัวดง,เก้าเลี้ยว,Nakhon Sawan,หัวดง,เก้าเลี้ยว,Nakhon Sawan,89,1993,11.40,29.01,23.58
36,37,2025,January,paddy,ลาดโพธิ์,บ้านลาด,Phetchaburi,สระแก้ว,เมืองสระแก้ว,Sa Kaeo,89,1993,317.70,349.30,54.57
37,38,2025,January,paddy,พนมรอก,ท่าตะโก,Nakhon Sawan,มะขามล้ม,บางปลาม้า,Suphan Buri,86,1915,194.66,235.65,49.56
38,39,2025,January,paddy,หนองหญ้าปล้อง,ทัพทัน,Uthai Thani,สระแก้ว,เมืองสุพรรณบุรี,Suphan Buri,85,1889,132.03,161.45,49.07
39,40,2025,January,paddy,โพธิ์ไทร,โพธิ์ไทร,Ubon Ratchathani,กระจาย,ป่าติ้ว,Yasothon,85,1889,110.12,148.02,44.64

### EDA

In [231]:
df.duplicated().sum()

np.int64(0)

In [240]:
numerical_features = df.select_dtypes(include=('int64','float64')).columns
categorical_features = df.select_dtypes(include='object').columns