In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from deep_translator import GoogleTranslator

In [43]:
df = pd.read_csv("/Users/srisuphachawla/Documents/DataScience_Projects/LogisticsDataset/Thai_logistics_inEnglishProcess")
df

,id,year,month,product,subdistrict_origin,district_origin,province_origin,subdistrict_destination,district_destination,province_destination,trips,shipping,average_distance,average_duration,average_speed
0,1,2568,January,paddy,ตาลสุม,Tansum,Ubon Ratchathani,กุดชมภู,Phibun Mangsahan,Ubon Ratchathani,405,9033,21.43,32.66,39.37
1,2,2568,January,paddy,พระอาจารย์,torpedo,Nakhon Nayok,ท่าสะอ้าน,Bang Pakong,Chachoengsao,403,8981,63.93,91.61,41.87
2,3,2568,January,paddy,คำหว้า,Tansum,Ubon Ratchathani,กุดชมภู,Phibun Mangsahan,Ubon Ratchathani,384,8567,21.89,39.93,32.89
3,4,2568,January,paddy,วังม้า,Lat Yao,Nakhon Sawan,ท่าฉนวน,Manorom,Chai Nat,331,7376,67.10,84.94,47.40
4,5,2568,January,paddy,เตย,purple thirty,Ubon Ratchathani,ยางโยภาพ,purple thirty,Ubon Ratchathani,320,7143,18.50,26.89,41.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346966,346967,2568,August,car,ทุ่งสุขลา,Sriracha,Chonburi,สุรศักดิ์,Sriracha,Chonburi,1,17,18.61,52.88,21.12
346967,346968,2568,August,car,ทุ่งสุขลา,Sriracha,Chonburi,ไร่ส้ม,Mueang Phetchaburi,Phetchaburi,1,17,236.98,332.48,42.77
346968,346969,2568,August,car,ทุ่งสุขลา,Sriracha,Chonburi,บางแก้ว,Mueang Samut Songkhram,Samut Songkhram,1,17,177.05,245.00,43.36
346969,346970,2568,August,car,ทุ่งสุขลา,Sriracha,Chonburi,คันนายาว,Khan Na Yao District,Bangkok,1,17,105.57,156.45,40.49
346970,346971,2568,August,car,ทุ่งสุขลา,Sriracha,Chonburi,บ้านใหม่,Mueang Nakhon Ratchasima,Nakhon Ratchasima,1,17,348.39,533.02,39.22

In [35]:
df.describe()

,id,year,trips,shipping,average_distance,average_duration,average_speed
count,346971.000000,346971.0,346971.000000,346971.000000,346971.000000,346971.000000,346971.000000
mean,173486.000000,2568.0,28.031945,776.947598,121.397510,156.876851,43.930749
std,100162.044463,0.0,163.843404,4922.222475,137.645385,175.312006,9.426172
min,1.000000,2568.0,1.000000,6.000000,3.000000,4.500000,15.000000
25%,86743.500000,2568.0,2.000000,40.000000,29.120000,44.960000,38.060000
50%,173486.000000,2568.0,5.000000,121.000000,74.950000,99.540000,45.000000
75%,260228.500000,2568.0,15.000000,369.000000,158.125000,199.210000,50.620000
max,346971.000000,2568.0,29978.000000,899332.000000,1480.180000,4444.170000,65.000000

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 346971 entries, 0 to 346970
Data columns (total 15 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       346971 non-null  int64
 1   year                     346971 non-null  int64
 2   month                    346971 non-null  object
 3   product                  346971 non-null  object
 4   subdistrict_origin       346971 non-null  object
 5   district_origin          346971 non-null  object
 6   province_origin          346971 non-null  object
 7   subdistrict_destination  346971 non-null  object
 8   district_destination     346971 non-null  object
 9   province_destination     346971 non-null  object
 10  trips                    346971 non-null  int64
 11  shipping                 346971 non-null  int64
 12  average_distance         346971 non-null  float64
 13  average_duration         346971 non-null  float64
 14  average_speed            346971 non-null  float64
dtypes: float64(3), int64(4), object(8)
memory usage: 39.7+ MB

In [45]:
print(df.nunique())

id                         346971
year                            1
month                           5
product                        21
subdistrict_origin           4138
district_origin               872
province_origin                77
subdistrict_destination      5447
district_destination          912
province_destination           77
trips                        1644
shipping                     8753
average_distance            48140
average_duration            55370
average_speed                4995
dtype: int64